name: seller_management
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # UI
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  extended_image: ^8.2.1
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  flex_color_scheme: ^7.3.1
  gap: ^3.0.1
  material_design_icons_flutter: ^7.0.7296
  badges: ^3.1.2
  grouped_list: ^6.0.0
  flutter_form_builder: ^9.3.0
  flutter_svg: ^2.0.10
  flutter_staggered_grid_view: ^0.7.0
  fl_chart: ^0.68.0
  lottie: ^3.1.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  buttons_tabbar: ^1.3.12
  shimmer_animation: ^2.1.0
  dropdown_button2: ^2.3.9
  flutter_html: ^3.0.0-beta.2
  html_editor_enhanced_plus: ^2.6.0
  package_info_plus: ^8.0.2
  flutter_rating_bar: ^4.0.1
  injectable_generator: ^2.0.0
  build_runner: ^2.0.0
  auto_animated_list: ^1.0.4
  location: ^7.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.7.0
  timeline_tile: ^2.0.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1
  animated_onboard:
     path: package/animated_onboard

  # State and Management
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  go_router: ^14.2.1
  shared_preferences: ^2.2.3
  get_it: ^7.7.0
  injectable: ^2.4.2
  form_builder_validators: ^11.0.0
  hold_on_pop: ^0.0.5
  encrypt: ^5.0.3
  pointycastle: ^3.7.3
  internet_connection_checker: ^1.0.0+1
  flutter_inappwebview: ^6.0.0 # You can specify the version you're using
  provider: ^6.0.5
  get: ^4.6.5
#  razorpay_flutter: ^1.3.7

  # Util
  intl: ^0.19.0
  dio: ^5.5.0
  fpdart: ^1.1.0
  equatable: ^2.0.5
  path_provider: ^2.1.3
  file_picker: ^8.0.5
  url_launcher: ^6.3.0
  talker_flutter: ^4.2.4
  talker_dio_logger: ^4.1.5
  share_plus: ^9.0.0
  toastification: ^2.0.0
  image_picker: ^1.1.2
  open_filex: ^4.4.0
  collection: ^1.18.0
  easy_localization: ^3.0.7
  pdf: ^3.10.8
  printing: ^5.12.0
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.3.1
  timeago: ^3.6.1
  pull_to_refresh: ^2.0.0
  riverpod_annotation: ^2.3.5
  animated_segmented_tab_control: ^2.0.0
  firebase_messaging: ^15.0.3
  firebase_core: ^3.2.0
  flutter_local_notifications: ^17.2.1
#  #payment
  payment_module:
    path: package/payment_module
  esewa_flutter_sdk:
    path: package/esewa_flutter_sdk
  razorpay_flutter: ^1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  build_runner: ^2.4.11
  injectable_generator: ^2.6.1
  riverpod_generator: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/svg/nav/
    - assets/svg/dash/
    - assets/lottie/
    - assets/lang/
    - assets/logo/
    - assets/illustration/
    - assets/icon/
    - assets/lang1/
    - assets/rive/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_logo.png"